[tool.poetry]
name = "weather-co2-station"
version = "0.1.0"
description = ""
authors = ["Yuval Adam <_@yuv.al>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
smbus = "^1.1.post2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
